# Access Route4Me's logistics-as-a-service API using our Node.js SDK
#
# Copyright (C) 2016-2017 Route4Me

# HEADER ??

sudo: false

language: node_js

node_js:
  - node
  - 4
  - 6
  - iojs
  - 7

matrix:
  allow_failures:
    - node_js: 7  # unstable upstream
    - node_js: 8  # not on travis

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install -g npm
  # - npm install -g gulp
  - npm install -g codecov
  - npm install -g bithound

script:
# - gulp build
  - npm run lint
  - npm test
  - npm run coverage
  - codecov
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git

deploy:
  provider: npm
  api_key: $NPM_API_KEY
  on:
    # tags: true                            # published only for tags
    node_js: 6                              # published only for one NPM version
    # repo: route4me/route4me-nodejs-sdk    # published only from ONE repo
